version: '3'

services:
  app:
    build: .
    restart: always
    command: carton exec perl watchers_eye
    volumes:
      - .:/app
    stdin_open: true
    tty: true
    depends_on: [tor]
  tor:
    image: dperson/torproxy:latest
    environment:
      TZ: Asia/Tokyo
